services:
  db:
    image: jef4267/matchsys-mysql:1.0
    container_name: matchsys-mysql
    restart: unless-stopped
    # 容器内存上限（8G机器建议先给 6G）
    mem_limit: 3g
    ports:
      - "6033:3306"
    environment:
      MYSQL_DATABASE: matchSys
      MYSQL_ROOT_PASSWORD: YourStrongPassword:123!
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
    networks:
      - matchsys-net

  web:
    image: jef4267/matchsys-web:1.0
    container_name: matchsys-web
    restart: unless-stopped
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    depends_on:
      - db
    networks:
      - matchsys-net
    environment:
      DB_NAME: matchSys
      DB_USER: bpmatch_user
      DB_PASSWORD: bpmatch_user_AbCdEfG
      DB_HOST: db
      DB_PORT: 3306
      OLLAMA_HOST: http://ollama:11434

  nginx:
    image: jef4267/matchsys-nginx:1.0
    container_name: matchsys-nginx
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
    networks:
      - matchsys-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - matchsys-net
    entrypoint:
      - /bin/sh
      - -c
      - >
        ollama serve & sleep 2 && ollama pull llama3.2:3b-instruct-q4_K_M && wait

      

volumes:
  mysql_data:
  ollama_data:

networks:
  matchsys-net:
    name: matchsys-net
