.git
__pycache__/
*.pyc
*.pyo
*.pyd
.env
.venv/
venv/
node_modules/
media/
staticfiles/
*.sqlite3
.DS_Store

credentials/
customer_contract/
docker_mysql_img/
docs/
frontend/
line_uploads/
logs/
nginx/
ss/

