
server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/home/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /matchSys/ {
        alias /var/www/matchSys/;
        try_files $uri $uri/ /matchSys/login.html;
    }

    location = /matchSys {
        return 301 /matchSys/;
    }

    location /api/ {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

